/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Clock: typeof import('./src/components/Clock.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCalendar: typeof import('./src/components/icons/IconCalendar.vue')['default']
    IconChat: typeof import('./src/components/icons/IconChat.vue')['default']
    IconClose: typeof import('./src/components/icons/IconClose.vue')['default']
    IconGift: typeof import('./src/components/icons/IconGift.vue')['default']
    IconHammer: typeof import('./src/components/icons/IconHammer.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconLogout: typeof import('./src/components/icons/IconLogout.vue')['default']
    IconMenu: typeof import('./src/components/icons/IconMenu.vue')['default']
    IconNotification: typeof import('./src/components/icons/IconNotification.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    IconSetting: typeof import('./src/components/icons/IconSetting.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    Plan: typeof import('./src/components/plan/Plan.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Star: typeof import('./src/components/effects/Star.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
